version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /cicd/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /cicd/docker-credentials/password
    DOCKER_REGISTRY_URL: /cicd/docker-registry/url
    SONAR_TOKEN: /cicd/sonar/sonar-token

phases:
  install:
    runtime-versions:
      python: 3.11
      java: corretto17
    commands:
      - echo "Starting install phase..."
      - nohup /usr/local/bin/dockerd-entrypoint.sh &  # Start Docker daemon
      - timeout 15 sh -c "until docker info; do echo 'Waiting for Docker...'; sleep 1; done"

  pre_build:
    commands:
      - echo "Running pre-build phase..."
      - echo "Preparing security scanning tools (optional)..."
      # Optional Trivy / Dependency Check / SonarScanner setup
      # Uncomment if needed
      # - wget https://github.com/aquasecurity/trivy/releases/download/v0.19.2/trivy_0.19.2_Linux-64bit.tar.gz
      # - tar zxvf trivy_0.19.2_Linux-64bit.tar.gz
      # - export PATH=$PATH:$PWD
      # - trivy filesystem --exit-code 0 --no-progress . >> trivyfilescan.txt

  build:
    commands:
      - echo "Running build phase..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/swiggy:latest" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/swiggy:latest"

  post_build:
    commands:
      - echo "Running post-build phase..."
      - |
        aws ses send-email \
          --from "devopssubroto@gmail.com" \
          --destination "ToAddresses=devopssubroto@gmail.com" \
          --message "Subject={Data=CodeBuild Status: $CODEBUILD_BUILD_ID,Charset=utf8},Body={Text={Data=Build status: $CODEBUILD_BUILD_STATUS,Charset=utf8}}" \
          --region "us-east-1"

artifacts:
  files:
    - appspec.yaml
