version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /cicd/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /cicd/docker-credentials/password
    DOCKER_REGISTRY_URL: /cicd/docker-registry/url
    SONAR_TOKEN: /cicd/sonar/sonar-token

phases:
  install:
    runtime-versions:
      python: 3.11
      java: corretto17
    commands:
      - echo "Starting install phase..."
      - nohup /usr/local/bin/dockerd-entrypoint.sh &  # Start Docker daemon
      - timeout 15 sh -c "until docker info; do echo 'Waiting for Docker...'; sleep 1; done"

  pre_build:
    commands:
      - echo "Running pre-build steps..."
      - echo "Docker registry: $DOCKER_REGISTRY_URL"

  build:
    commands:
      - echo "Running build phase..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/swiggy:latest" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/swiggy:latest"

  post_build:
    commands:
      - echo "Build completed at `date`"
